### ISSUE TITLE
Fee controller can rug pull users

### ISSUE THREAD

**Issue by bulej93** [Harpieio/contracts#2]
the fee controller has the ability to withdraw fees which come directly from the contract. this means he can take all the users tokens. the fees should be moved to another separate contract when the user claims his tokens and pays the fee.

Remove the withdrawalpayments function, only allow users to withdraw their tokens

https://github.com/Harpieio/contracts/blob/97083d7ce8ae9d85e29a139b1e981464ff92b89e/contracts/Vault.sol#L156-L160

**Comment by dnlchong** [comment]
`.transfer(_amount)` is only able to transfer ETH, not tokens. This function is designed for us to withdraw the fees we take, which are in ETH.
